# logging 레벨 설정
logging:
  level:
#    root: info
    sql: error
    org.springframework.web: debug

spring:
  # Overloaded POST 사용
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  # Thymeleaf decoupled logic 사용
  thymeleaf3:
    decoupled-logic: true
  # H2 Database 설정
  h2:
    console:
      enabled: true
  datasource:
    username: root
    password: password
    
# session
server:
  servlet:
    session:
      timeout: 10m # 기본이 30분이고 최소는 1분입니다.